TUTORIAL MAPPING QUERIES

-- ALL TUTORIALS
SELECT DISTINCT("ID")
FROM IMS_TASK
WHERE TASK_TYPE = 'TUTORIAL'
AND TASK_STATUS IS NULL

-- TUTORIALS TO GROUPS
SELECT 
   	child."ID" as "Tutorial ID", 
	child.TITLE,
	parent."ID" as "Group ID",
	parent.TITLE
FROM IMSDBUSER.IMS_TASK_TO_PARENT
	INNER JOIN IMSDBUSER.IMS_TASK AS child
	ON IMS_TASK_TO_PARENT.CHILD_TASK_ID = child.ID
	INNER JOIN IMSDBUSER.IMS_TASK AS parent
	ON IMS_TASK_TO_PARENT.PARENT_TASK_ID = parent.ID
WHERE child.TASK_TYPE = 'TUTORIAL';


-- TUTORIALS TO MISSIONS
SELECT 
	child."ID" as "Tutorial ID", 
	child.TITLE,
	parent."ID" as "Mission ID", 
	parent.TITLE
FROM IMS_COMPLETION_PATH_TO_TASK
	INNER JOIN IMS_COMPLETION_PATH
	ON IMS_COMPLETION_PATH.ID = IMS_COMPLETION_PATH_TO_TASK.PATH_ID
	INNER JOIN IMS_TASK AS child
	ON child.ID = IMS_COMPLETION_PATH_TO_TASK.TASK_ID
	INNER JOIN IMS_TASK AS parent
	ON parent.ID = IMS_COMPLETION_PATH.MISSION_ID
WHERE CHILD.TASK_TYPE = 'TUTORIAL'
AND PARENT.TITLE NOT LIKE '#%'
AND PARENT.TITLE NOT LIKE '% Savvy'

-- GROUPS TO MISSIONS
SELECT 
	child."ID" as "Group ID", 
	child.TITLE,
	parent."ID" as "Mission ID", 
	parent.TITLE
FROM IMS_COMPLETION_PATH_TO_TASK
	INNER JOIN IMS_COMPLETION_PATH
	ON IMS_COMPLETION_PATH.ID = IMS_COMPLETION_PATH_TO_TASK.PATH_ID
	INNER JOIN IMS_TASK AS child
	ON child.ID = IMS_COMPLETION_PATH_TO_TASK.TASK_ID
	INNER JOIN IMS_TASK AS parent
	ON parent.ID = IMS_COMPLETION_PATH.MISSION_ID
WHERE CHILD.TASK_TYPE = 'GROUP'
AND PARENT.TITLE NOT LIKE '#%'
AND PARENT.TITLE NOT LIKE '% Savvy'








