-- Mission Completions
SELECT IMS_TASK."ID" AS "Mission ID", 
	COUNT(IMS_TASK_RECORD."USER_ID") AS "Mission Completions"
FROM IMS_TASK_RECORD
	INNER JOIN "IMS_TASK"
	ON IMS_TASK_RECORD."TASK_ID" = IMS_TASK."ID"
WHERE IMS_TASK."TASK_TYPE" = 'MISSION'
	AND YEAR(IMS_TASK_RECORD."CREATED_AT") = 2021
	AND MONTH(IMS_TASK_RECORD."CREATED_AT") = 10
	AND STATUS = 'COMPLETED'
	AND IMS_TASK_RECORD."UPDATED_AT" IS NOT NULL
GROUP BY IMS_TASK."ID"
ORDER BY "Mission Completions" DESC


-- Group Completions
SELECT IMS_TASK."ID" AS "Group ID", 
	COUNT(IMS_TASK_RECORD."USER_ID") AS "Group Completions"
FROM IMS_TASK_RECORD
	INNER JOIN "IMS_TASK"
	ON IMS_TASK_RECORD."TASK_ID" = IMS_TASK."ID"
WHERE IMS_TASK."TASK_TYPE" = 'GROUP'
	AND YEAR(IMS_TASK_RECORD."CREATED_AT") = 2021
	AND MONTH(IMS_TASK_RECORD."CREATED_AT") = 10
	AND STATUS = 'COMPLETED'
	AND IMS_TASK_RECORD."UPDATED_AT" IS NOT NULL
GROUP BY IMS_TASK."ID"
ORDER BY "Group Completions" DESC


-- Tutorial Completions

SELECT IMS_TASK."ID" AS "Tutorial ID", 
	COUNT(IMS_TASK_RECORD."USER_ID") AS "Tutorial Completions"
FROM IMS_TASK_RECORD
	INNER JOIN "IMS_TASK"
	ON IMS_TASK_RECORD."TASK_ID" = IMS_TASK."ID"
WHERE IMS_TASK."TASK_TYPE" = 'TUTORIAL'
	AND YEAR(IMS_TASK_RECORD."CREATED_AT") = 2021
	AND MONTH(IMS_TASK_RECORD."CREATED_AT") = 10
	AND STATUS = 'COMPLETED'
	AND IMS_TASK_RECORD."UPDATED_AT" IS NOT NULL
GROUP BY IMS_TASK."ID"
ORDER BY "Tutorial Completions" DESC


-- Tutorial Starts







-- Step Completions








-- Step Failures






