-- Mission Completions
SELECT IMS_TASK."ID" AS "Mission ID", 
	COUNT(IMS_TASK_RECORD."USER_ID") AS "Mission Completions"
FROM IMS_TASK_RECORD
	INNER JOIN "IMS_TASK"
	ON IMS_TASK_RECORD."TASK_ID" = IMS_TASK."ID"
WHERE IMS_TASK."TASK_TYPE" = 'MISSION'
	AND YEAR(IMS_TASK_RECORD."CREATED_AT") = 2021
	AND MONTH(IMS_TASK_RECORD."CREATED_AT") = 10
	AND STATUS = 'COMPLETED'
	AND IMS_TASK_RECORD."UPDATED_AT" IS NOT NULL
GROUP BY IMS_TASK."ID"
ORDER BY "Mission Completions" DESC


-- Group Completions
SELECT IMS_TASK."ID" AS "Group ID", 
	COUNT(IMS_TASK_RECORD."USER_ID") AS "Group Completions"
FROM IMS_TASK_RECORD
	INNER JOIN "IMS_TASK"
	ON IMS_TASK_RECORD."TASK_ID" = IMS_TASK."ID"
WHERE IMS_TASK."TASK_TYPE" = 'GROUP'
	AND YEAR(IMS_TASK_RECORD."CREATED_AT") = 2021
	AND MONTH(IMS_TASK_RECORD."CREATED_AT") = 10
	AND STATUS = 'COMPLETED'
	AND IMS_TASK_RECORD."UPDATED_AT" IS NOT NULL
GROUP BY IMS_TASK."ID"
ORDER BY "Group Completions" DESC


-- Tutorial Completions

SELECT IMS_TASK."ID" AS "Tutorial ID", 
	COUNT(IMS_TASK_RECORD."USER_ID") AS "Tutorial Completions"
FROM IMS_TASK_RECORD
	INNER JOIN "IMS_TASK"
	ON IMS_TASK_RECORD."TASK_ID" = IMS_TASK."ID"
WHERE IMS_TASK."TASK_TYPE" = 'TUTORIAL'
	AND YEAR(IMS_TASK_RECORD."CREATED_AT") = 2021
	AND MONTH(IMS_TASK_RECORD."CREATED_AT") = 10
	AND STATUS = 'COMPLETED'
	AND IMS_TASK_RECORD."UPDATED_AT" IS NOT NULL
GROUP BY IMS_TASK."ID"
ORDER BY "Tutorial Completions" DESC


-- Tutorial Starts

SELECT TASK2."ID" AS "Tutorial ID", 
	COUNT(DISTINCT(IMS_TASK_RECORD."USER_ID")) AS "Tutorial Starts"
FROM IMS_TASK_RECORD
	LEFT OUTER JOIN "IMS_TASK"
	ON IMS_TASK_RECORD."TASK_ID" = IMS_TASK."ID"
	LEFT OUTER JOIN "IMS_TASK_TO_PARENT"
	ON IMS_TASK."ID" = "IMS_TASK_TO_PARENT".CHILD_TASK_ID
	LEFT OUTER JOIN IMS_TASK AS TASK2
	ON IMS_TASK_TO_PARENT.PARENT_TASK_ID = TASK2."ID"
WHERE IMS_TASK."TASK_TYPE" = 'STEP'
	AND YEAR(IMS_TASK_RECORD."UPDATED_AT") = 2021
	AND MONTH(IMS_TASK_RECORD."UPDATED_AT") = 10
	AND STATUS = 'COMPLETED'
GROUP BY TASK2."ID", IMS_TASK."TASK_TYPE"
ORDER BY "Tutorial Starts" DESC
LIMIT 2000;



-- Step Completions

   SELECT 
    TASK2."ID" as "Tutorial ID",
    IMS_TASK."TITLE" AS "Step", 
	COUNT(IMS_TASK_RECORD."USER_ID") AS "Times Completed"
	
FROM IMS_TASK_RECORD 

LEFT JOIN "IMS_TASK" ON IMS_TASK_RECORD."TASK_ID" = IMS_TASK."ID"
LEFT JOIN IMS_TASK_TO_PARENT ON IMS_TASK."ID" = IMS_TASK_TO_PARENT.CHILD_TASK_ID
LEFT JOIN IMS_TASK AS TASK2 ON IMS_TASK_TO_PARENT.PARENT_TASK_ID = TASK2."ID"
	
WHERE IMS_TASK."TASK_TYPE" = 'STEP'
	AND YEAR(IMS_TASK_RECORD."CREATED_AT") = 2021
	AND IMS_TASK_RECORD.CREATED_AT > '2021-9-27'
	AND STATUS = 'COMPLETED'
	AND IMS_TASK_RECORD."UPDATED_AT" IS NOT NULL
GROUP BY IMS_TASK."TITLE", IMS_TASK."ID", TASK2."ID",  TASK2.TITLE
ORDER BY "Times Completed" DESC


-- Step Failures

    SELECT 
	TUTORIAL_ID as "Tutorial ID",
    IMS_STEP_FAILURE."TITLE" AS "Step", 
 COUNT(IMS_STEP_FAILURE."TUTORIAL_ID") AS "Times Failed"


FROM IMS_STEP_FAILURE
	LEFT JOIN "IMS_TASK" ON IMS_STEP_FAILURE."TUTORIAL_ID" = IMS_TASK."ID"
	
WHERE 
    year(IMS_STEP_FAILURE."CREATED_AT") = 2021
    AND IMS_STEP_FAILURE.UPDATED_AT > '2021-9-27'
 
GROUP BY IMS_STEP_FAILURE."TITLE", 
	IMS_STEP_FAILURE.TUTORIAL_ID,
	IMS_TASK."TITLE"
    
    ORDER BY "Times Failed" DESC





